/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Form;
import Koneksi.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import tmasch.UserSession;

/**
 *
 * @author Draugr
 */
public class CreateTicketPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateTicketPanel
     */
    public CreateTicketPanel() {
        initComponents();
        txtuser.setEditable(false);
        String LoginUser = tmasch.UserSession.getFullName();
        txtuser.setText(LoginUser);
    }

    private void resetForm() {
        cbcat.setSelectedIndex(0);
        txtsub.setText("");
        txtdesc.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TittlePanel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbcat = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtsub = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdesc = new javax.swing.JTextArea();
        btnsubmit = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();

        TittlePanel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TittlePanel.setText("Create Ticket Form");

        jLabel2.setText("Created By");

        jLabel3.setText("Category");

        cbcat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Kategori --", "Akademik ", "Non-Akademik", "Legalisir", "Permohonan Data/Info", "Pengajuan Perubahan Data" }));

        jLabel1.setText("Ticket Subject");

        jLabel4.setText("Description");

        txtdesc.setColumns(20);
        txtdesc.setRows(5);
        jScrollPane1.setViewportView(txtdesc);

        btnsubmit.setText("Submit");
        btnsubmit.addActionListener(this::btnsubmitActionPerformed);

        btncancel.setText("Cancel");
        btncancel.addActionListener(this::btncancelActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(TittlePanel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(cbcat, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtuser))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(19, 19, 19)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnsubmit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btncancel))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                            .addComponent(txtsub))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(TittlePanel)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbcat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsub, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsubmit)
                    .addComponent(btncancel))
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
    int konfirmasi = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin membatalkan dan mengosongkan isi form?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (konfirmasi == JOptionPane.YES_OPTION) {
            resetForm();
        }
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        String kategoriTeks = cbcat.getSelectedItem() != null ? cbcat.getSelectedItem().toString().trim() : "";
        String subjek = txtsub.getText().trim();
        String deskripsi = txtdesc.getText().trim();

        // 1. Validasi jika form masih ada yang kosong atau belum memilih
        if (kategoriTeks.isEmpty() || kategoriTeks.startsWith("--") || subjek.isEmpty() || deskripsi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mohon lengkapi semua data form tiket!", "Validasi Gagal", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. KONTROL ID KATEGORI MENGGUNAKAN EQUALS IGNORE CASE (Paling Aman dari Typo)
        int categoryId = 0;
        if (kategoriTeks.equalsIgnoreCase("Akademik")) {
            categoryId = 1;
        } else if (kategoriTeks.equalsIgnoreCase("Non-Akademik")) {
            categoryId = 2;
        } else if (kategoriTeks.equalsIgnoreCase("Legalisir")) {
            categoryId = 3;
        } else if (kategoriTeks.equalsIgnoreCase("Permohonan Data/Info") || kategoriTeks.equalsIgnoreCase("Permohonan Data")) {
            categoryId = 4;
        } else if (kategoriTeks.equalsIgnoreCase("Pengajuan Perubahan Data")) {
            categoryId = 5;
        }

        // VALIDASI TAMBAHAN: Jika categoryId tetap 0 (tidak masuk ke kondisi manapun), hentikan proses eksekusi
        if (categoryId == 0) {
            JOptionPane.showMessageDialog(this, "Kategori '" + kategoriTeks + "' tidak dikenali oleh sistem.\nPeriksa kembali teks pada model Combo Box Anda!", "Error Kategori", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // ID User pembuat tiket (Sesuai user admin bawaan SQL kalian yang memiliki ID = 1)
        int idUserLogin = tmasch.UserSession.getId(); 

        // ID Status untuk 'OPEN' berdasarkan tabel `statuses` kalian adalah 1
        int statusId = 1; 

        // 3. Eksekusi Query Insert ke Database tmasch_db
        String sql = "INSERT INTO tickets (title, description, category_id, status_id, created_by, created_at) VALUES (?, ?, ?, ?, ?, NOW())";

        try {
            // Membuka koneksi ke database local
            Connection conn = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/tmasch_db", "root", "");

            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, subjek);       // title
            ps.setString(2, deskripsi);    // description
            ps.setInt(3, categoryId);      // category_id (Pasti bernilai 1-5, tidak mungkin 0)
            ps.setInt(4, statusId);        // status_id (1 = OPEN)
            ps.setInt(5, idUserLogin);     // created_by (1 = Admin)

            int statusSimpan = ps.executeUpdate();
            if (statusSimpan > 0) {
                JOptionPane.showMessageDialog(this, "Tiket baru berhasil dibuat dengan status OPEN!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                resetForm(); // Bersihkan field form
            }

            ps.close();
            conn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan tiket ke database:\n" + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnsubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TittlePanel;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JComboBox<String> cbcat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtdesc;
    private javax.swing.JTextField txtsub;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
