/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;
import Koneksi.koneksi; 
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import tmasch.UserSession;
/**
 *
 * @author Draugr
 */
public class LoginForm extends javax.swing.JFrame {
    int xx, xy;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginForm.class.getName());

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BorderJpanel = new javax.swing.JPanel();
        InsideJpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        ExitBt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        BorderJpanel.setBackground(new java.awt.Color(153, 153, 153));
        BorderJpanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BorderJpanelMouseDragged(evt);
            }
        });
        BorderJpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BorderJpanelMousePressed(evt);
            }
        });

        InsideJpanel.setBackground(new java.awt.Color(204, 204, 204));
        InsideJpanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                InsideJpanelMouseDragged(evt);
            }
        });
        InsideJpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                InsideJpanelMousePressed(evt);
            }
        });

        jLabel1.setText("Username");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("<html><center>T-Masch <br>(Ticketing Management System <br>Administration School)</center></html>");

        jLabel3.setText("Password");

        btnLogin.setText("Login");
        btnLogin.addActionListener(this::btnLoginActionPerformed);

        ExitBt.setBackground(new java.awt.Color(102, 102, 102));
        ExitBt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ExitBt.setText("X");
        ExitBt.addActionListener(this::ExitBtActionPerformed);

        javax.swing.GroupLayout InsideJpanelLayout = new javax.swing.GroupLayout(InsideJpanel);
        InsideJpanel.setLayout(InsideJpanelLayout);
        InsideJpanelLayout.setHorizontalGroup(
            InsideJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsideJpanelLayout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addComponent(ExitBt)
                .addContainerGap())
            .addGroup(InsideJpanelLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addGroup(InsideJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InsideJpanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18))
                    .addGroup(InsideJpanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(21, 21, 21)))
                .addGroup(InsideJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogin)
                    .addGroup(InsideJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                        .addComponent(txtUsername)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InsideJpanelLayout.setVerticalGroup(
            InsideJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsideJpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InsideJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExitBt))
                .addGap(69, 69, 69)
                .addGroup(InsideJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InsideJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnLogin)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BorderJpanelLayout = new javax.swing.GroupLayout(BorderJpanel);
        BorderJpanel.setLayout(BorderJpanelLayout);
        BorderJpanelLayout.setHorizontalGroup(
            BorderJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BorderJpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InsideJpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BorderJpanelLayout.setVerticalGroup(
            BorderJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BorderJpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InsideJpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BorderJpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BorderJpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String username = txtUsername.getText().trim();
        String password = new String(txtPassword.getPassword()).trim();

        if (username.isEmpty() || password.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Username dan Password tidak boleh kosong!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            Koneksi.koneksi db = new Koneksi.koneksi(); 
            java.sql.Connection conn = db.connect();

            String sql = "SELECT * FROM users WHERE username = ? AND password = ?";
            java.sql.PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, username);
            ps.setString(2, password);

            java.sql.ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                tmasch.UserSession.setId(rs.getInt("id"));
                tmasch.UserSession.setUsername(rs.getString("username"));
                tmasch.UserSession.setFullName(rs.getString("full_name"));
                tmasch.UserSession.setRoleId(rs.getInt("role_id"));

                javax.swing.JOptionPane.showMessageDialog(this, "Login Berhasil!\nSelamat datang, " + tmasch.UserSession.getFullName(), "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                Form.MainDashboard dashboard = new Form.MainDashboard();
                dashboard.setVisible(true);

               
                this.dispose();

            } else {
                // Jika data tidak ditemukan
                javax.swing.JOptionPane.showMessageDialog(this, "Username atau Password salah!", "Gagal Login", javax.swing.JOptionPane.ERROR_MESSAGE);
            }

            // Tutup statement dan result set
            rs.close();
            ps.close();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Terjadi kesalahan sistem: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void ExitBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitBtActionPerformed

    private void BorderJpanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BorderJpanelMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_BorderJpanelMousePressed

    private void BorderJpanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BorderJpanelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_BorderJpanelMouseDragged

    private void InsideJpanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsideJpanelMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_InsideJpanelMousePressed

    private void InsideJpanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsideJpanelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_InsideJpanelMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BorderJpanel;
    private javax.swing.JButton ExitBt;
    private javax.swing.JPanel InsideJpanel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
