/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

/**
 *
 * @author Draugr
 */
public class MainDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainDashboard.class.getName());

    /**
     * Creates new form MainDashboard
     */
public MainDashboard() {
        initComponents();
        this.setSize(900, 600);
        this.setLocationRelativeTo(null);

        // Panel: buat tiket
        Form.CreateTicketPanel halCreateTicket = new Form.CreateTicketPanel();
        panelKontenUtama.add(halCreateTicket, "buka_tiket");

        // Panel: kelola tiket
        Form.TicketManagement halManagement = new Form.TicketManagement(
            tmasch.UserSession.getRoleId(),
            tmasch.UserSession.getId());
        panelKontenUtama.add(halManagement, "kelola_tiket");

        // Panel: laporan
        Form.ReportPanel halLaporan = new Form.ReportPanel();
        panelKontenUtama.add(halLaporan, "laporan");
        
        aturMenuBerdasarkanRole();

        // Tampilkan halaman awal
        java.awt.CardLayout cl = (java.awt.CardLayout) panelKontenUtama.getLayout();
        cl.show(panelKontenUtama, "buka_tiket");

        tampilkanSambutanUser();
    }

    private void tampilkanSambutanUser() {
        // 1. Ambil data nama lengkap dan nama role dari UserSession
        String namaUser = tmasch.UserSession.getFullName();
        int roleId = tmasch.UserSession.getRoleId();
        String namaRole = switch (roleId) {
                case 1 -> "Admin";
                case 2 -> "Guru / Staff";
                case 3 -> "Siswa";
                default -> "User";
            };
            lblWelcome.setText("<html>Halo, <b>" + namaUser + "</b><br><small>Roles anda :" + namaRole + "</small></html>");
    }

    /**
    * Mengatur visibilitas tombol sidebar berdasarkan role user yang login.
    * Role 1 = Admin   → semua menu tampil
    * Role 2 = Guru    → Create & Manage Ticket (tanpa Laporan)
    * Role 3 = Siswa   → hanya Create Ticket
    */
    private void aturMenuBerdasarkanRole() {
       int roleId = tmasch.UserSession.getRoleId();

       switch (roleId) {
           case 1 -> { // Admin: akses penuh
               btnCreateTickett.setVisible(true);
               btnManageTicket.setVisible(true);
               btnLaporan.setVisible(true);
               btnUsers.setVisible(true);
               btnPriority.setVisible(true);
               btnCategory.setVisible(true);
               btnRoles.setVisible(true);
               btnStatus.setVisible(true);           }
           case 2 -> { // Guru/Staff: tidak bisa lihat laporan
               btnCreateTickett.setVisible(true);
               btnManageTicket.setVisible(true);
               btnLaporan.setVisible(false);
               btnUsers.setVisible(false);
               btnPriority.setVisible(false);
               btnCategory.setVisible(false);
               btnRoles.setVisible(false);
               btnStatus.setVisible(false); 
           }
           case 3 -> { // Siswa: hanya buat tiket
               btnCreateTickett.setVisible(true);
               btnManageTicket.setVisible(false);
               btnLaporan.setVisible(false);
               btnUsers.setVisible(false);
               btnPriority.setVisible(false);
               btnCategory.setVisible(false);
               btnRoles.setVisible(false);
               btnStatus.setVisible(false);
           }
           default -> { // Role tidak dikenal: sembunyikan semua kecuali create
               btnCreateTickett.setVisible(true);
               btnManageTicket.setVisible(false);
               btnLaporan.setVisible(false);
               btnUsers.setVisible(false);
               btnPriority.setVisible(false);
               btnCategory.setVisible(false);
               btnRoles.setVisible(false);
               btnStatus.setVisible(false);               

               // Opsional: tampilkan peringatan
               javax.swing.JOptionPane.showMessageDialog(this,
                   "Role tidak dikenali (ID: " + roleId + ").\nAkses dibatasi.",
                   "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
           }
       }
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSidebar = new javax.swing.JPanel();
        btnCreateTickett = new javax.swing.JButton();
        btnManageTicket = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();
        btnLaporan = new javax.swing.JButton();
        btnUsers = new javax.swing.JButton();
        btnRoles = new javax.swing.JButton();
        btnCategory = new javax.swing.JButton();
        btnStatus = new javax.swing.JButton();
        btnPriority = new javax.swing.JButton();
        panelKontenUtama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelSidebar.setBackground(new java.awt.Color(102, 102, 102));
        panelSidebar.setMaximumSize(new java.awt.Dimension(240, 32767));
        panelSidebar.setPreferredSize(new java.awt.Dimension(240, 400));

        btnCreateTickett.setText("Create Ticket");
        btnCreateTickett.addActionListener(this::btnCreateTickettActionPerformed);

        btnManageTicket.setText("Manage Ticket");
        btnManageTicket.addActionListener(this::btnManageTicketActionPerformed);

        lblWelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome.setText("aiwodhawubfoawubfouawbfo");
        lblWelcome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblWelcome.setMaximumSize(new java.awt.Dimension(108, 90));
        lblWelcome.setMinimumSize(new java.awt.Dimension(100, 16));

        btnLaporan.setText("Laporan");
        btnLaporan.addActionListener(this::btnLaporanActionPerformed);

        btnUsers.setText("Users");
        btnUsers.addActionListener(this::btnUsersActionPerformed);

        btnRoles.setText("Roles");
        btnRoles.addActionListener(this::btnRolesActionPerformed);

        btnCategory.setText("Categories");
        btnCategory.addActionListener(this::btnCategoryActionPerformed);

        btnStatus.setText("Statuses");
        btnStatus.addActionListener(this::btnStatusActionPerformed);

        btnPriority.setText("Priorities");
        btnPriority.addActionListener(this::btnPriorityActionPerformed);

        javax.swing.GroupLayout panelSidebarLayout = new javax.swing.GroupLayout(panelSidebar);
        panelSidebar.setLayout(panelSidebarLayout);
        panelSidebarLayout.setHorizontalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSidebarLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnManageTicket, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                .addComponent(btnCreateTickett, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSidebarLayout.createSequentialGroup()
                                    .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(14, 14, 14)))))
                    .addGroup(panelSidebarLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelSidebarLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(btnUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelSidebarLayout.createSequentialGroup()
                                .addComponent(btnStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPriority, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelSidebarLayout.createSequentialGroup()
                                .addComponent(btnCategory)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRoles, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        panelSidebarLayout.setVerticalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateTickett)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManageTicket)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLaporan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addComponent(btnUsers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRoles)
                    .addComponent(btnCategory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStatus)
                    .addComponent(btnPriority))
                .addGap(38, 38, 38))
        );

        getContentPane().add(panelSidebar, java.awt.BorderLayout.WEST);

        panelKontenUtama.setBackground(new java.awt.Color(204, 204, 204));
        panelKontenUtama.setLayout(new java.awt.CardLayout());
        getContentPane().add(panelKontenUtama, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateTickettActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateTickettActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout) panelKontenUtama.getLayout();
        cl.show(panelKontenUtama, "buka_tiket");
    }//GEN-LAST:event_btnCreateTickettActionPerformed

    private void btnManageTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageTicketActionPerformed
        int roleId = tmasch.UserSession.getRoleId();
        if (roleId != 1 && roleId != 2) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Anda tidak memiliki akses ke menu ini.",
                "Akses Ditolak", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        java.awt.CardLayout cl = (java.awt.CardLayout) panelKontenUtama.getLayout();
        cl.show(panelKontenUtama, "kelola_tiket");
    }//GEN-LAST:event_btnManageTicketActionPerformed

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanActionPerformed
        if (tmasch.UserSession.getRoleId() != 1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Anda tidak memiliki akses ke menu ini.",
                "Akses Ditolak", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        java.awt.CardLayout cl = (java.awt.CardLayout) panelKontenUtama.getLayout();
        cl.show(panelKontenUtama, "laporan");
    }//GEN-LAST:event_btnLaporanActionPerformed

    private void btnCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryActionPerformed
        if (tmasch.UserSession.getRoleId() != 1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Anda tidak memiliki akses ke menu ini.",
                "Akses Ditolak", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        Form.categories formUser = new Form.categories();
        formUser.setLocationRelativeTo(null);
        formUser.setVisible(true);
    }//GEN-LAST:event_btnCategoryActionPerformed

    private void btnUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersActionPerformed
        if (tmasch.UserSession.getRoleId() != 1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Anda tidak memiliki akses ke menu ini.",
                "Akses Ditolak", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        Form.user formUser = new Form.user();
        formUser.setLocationRelativeTo(null);
        formUser.setVisible(true);
    }//GEN-LAST:event_btnUsersActionPerformed

    private void btnRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRolesActionPerformed
        if (tmasch.UserSession.getRoleId() != 1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Anda tidak memiliki akses ke menu ini.",
                "Akses Ditolak", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        Form.roles formUser = new Form.roles();
        formUser.setLocationRelativeTo(null);
        formUser.setVisible(true);
    }//GEN-LAST:event_btnRolesActionPerformed

    private void btnStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatusActionPerformed
        if (tmasch.UserSession.getRoleId() != 1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Anda tidak memiliki akses ke menu ini.",
                "Akses Ditolak", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        Form.statuses formUser = new Form.statuses();
        formUser.setLocationRelativeTo(null);
        formUser.setVisible(true);
    }//GEN-LAST:event_btnStatusActionPerformed

    private void btnPriorityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPriorityActionPerformed
        if (tmasch.UserSession.getRoleId() != 1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Anda tidak memiliki akses ke menu ini.",
                "Akses Ditolak", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        Form.priorities formUser = new Form.priorities();
        formUser.setLocationRelativeTo(null);
        formUser.setVisible(true);
    }//GEN-LAST:event_btnPriorityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCategory;
    private javax.swing.JButton btnCreateTickett;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnManageTicket;
    private javax.swing.JButton btnPriority;
    private javax.swing.JButton btnRoles;
    private javax.swing.JButton btnStatus;
    private javax.swing.JButton btnUsers;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel panelKontenUtama;
    private javax.swing.JPanel panelSidebar;
    // End of variables declaration//GEN-END:variables
}
