/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

/**
 *
 * @author Draugr
 */
public class MainDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainDashboard.class.getName());

    /**
     * Creates new form MainDashboard
     */
public MainDashboard() {
        initComponents();
        this.setSize(900, 600);
        this.setLocationRelativeTo(null);

        // Panel: buat tiket
        Form.CreateTicketPanel halCreateTicket = new Form.CreateTicketPanel();
        panelKontenUtama.add(halCreateTicket, "buka_tiket");

        // Panel: kelola tiket
        Form.TicketManagement halManagement = new Form.TicketManagement(
            tmasch.UserSession.getRoleId(),
            tmasch.UserSession.getId());
        panelKontenUtama.add(halManagement, "kelola_tiket");

        // Panel: laporan
//        Form.ReportPanel halLaporan = new Form.ReportPanel();
//        panelKontenUtama.add(halLaporan, "laporan");

        // Tampilkan halaman awal
        java.awt.CardLayout cl = (java.awt.CardLayout) panelKontenUtama.getLayout();
        cl.show(panelKontenUtama, "buka_tiket");

        tampilkanSambutanUser();
    }

private void tampilkanSambutanUser() {
    // 1. Ambil data nama lengkap dan nama role dari UserSession
    String namaUser = tmasch.UserSession.getFullName();
    int roleId = tmasch.UserSession.getRoleId();
    String namaRole = switch (roleId) {
            case 1 -> "Admin";
            case 2 -> "Guru / Staff";
            case 3 -> "Siswa";
            default -> "User";
        };
        lblWelcome.setText("<html>Halo, <b>" + namaUser + "</b><br><small>" + namaRole + "</small></html>");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSidebar = new javax.swing.JPanel();
        btnCreateTickett = new javax.swing.JButton();
        btnManageTicket = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();
        btnLaporan = new javax.swing.JButton();
        panelKontenUtama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelSidebar.setBackground(new java.awt.Color(102, 102, 102));
        panelSidebar.setPreferredSize(new java.awt.Dimension(150, 404));

        btnCreateTickett.setText("Create Ticket");
        btnCreateTickett.addActionListener(this::btnCreateTickettActionPerformed);

        btnManageTicket.setText("Manage Ticket");
        btnManageTicket.addActionListener(this::btnManageTicketActionPerformed);

        lblWelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome.setText("aiwodhawubfoawubfouawbfo");
        lblWelcome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblWelcome.setMaximumSize(new java.awt.Dimension(108, 90));
        lblWelcome.setMinimumSize(new java.awt.Dimension(100, 16));

        btnLaporan.setText("Laporan");
        btnLaporan.addActionListener(this::btnLaporanActionPerformed);

        javax.swing.GroupLayout panelSidebarLayout = new javax.swing.GroupLayout(panelSidebar);
        panelSidebar.setLayout(panelSidebarLayout);
        panelSidebarLayout.setHorizontalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCreateTickett, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelSidebarLayout.setVerticalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCreateTickett)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManageTicket)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLaporan)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        getContentPane().add(panelSidebar, java.awt.BorderLayout.WEST);

        panelKontenUtama.setBackground(new java.awt.Color(204, 204, 204));
        panelKontenUtama.setLayout(new java.awt.CardLayout());
        getContentPane().add(panelKontenUtama, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateTickettActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateTickettActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout) panelKontenUtama.getLayout();
        cl.show(panelKontenUtama, "buka_tiket");
    }//GEN-LAST:event_btnCreateTickettActionPerformed

    private void btnManageTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageTicketActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout) panelKontenUtama.getLayout();
        cl.show(panelKontenUtama, "kelola_tiket");
    }//GEN-LAST:event_btnManageTicketActionPerformed

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout) panelKontenUtama.getLayout();
        cl.show(panelKontenUtama, "laporan");
    }//GEN-LAST:event_btnLaporanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateTickett;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnManageTicket;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel panelKontenUtama;
    private javax.swing.JPanel panelSidebar;
    // End of variables declaration//GEN-END:variables
}
